version: '3.8'
services:
  traefik:
    image: ${TRAEFIK_IMAGE:-docker.io/library/traefik:v3.5.0}
    ports:
      - 80:80
      - 443:443
      # --> (Optional) Enable Dashboard, don't do in production
      - 8080:8080
      # <--
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ${DATA_VOLUME:?ERROR DATA_VOLUME NOT SET}/config:/etc/traefik:ro
      - ${DATA_VOLUME:?ERROR DATA_VOLUME NOT SET}/certs:/var/traefik/certs:rw
      - ${DATA_VOLUME:?ERROR DATA_VOLUME NOT SET}/logs:/var/traefik/logs
    environment:
      - TZ=${TZ:-Africa/Lagos}
      - DOMAIN=${DOMAIN:?ERROR DOMAIN NOT SET}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN:?ERROR CF_DNS_API_TOKEN NOT SET}
      - CF_API_EMAIL=${CF_API_EMAIL:-labs@semicolon.africa}
    networks:
      - edge
    command:
      # Global
      - "--global.checkNewVersion=false"
      - "--global.sendAnonymousUsage=false"
      # Observability Debug & logging
      - "--log.level=${TRAEFIK_LOG_LEVEL:-DEBUG}"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      # - "--log.filePath=/var/traefik/log/traefik.log"
      - "--accesslog.filePath=/var/traefik/logs/access.log"
      # Common Properties
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # - "--providers.docker.network=enumverse_frontend_net"
      # Docker socket
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      # Enable Docker Swarm Provider 
      - "--providers.swarm=true"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      # - "--providers.file.filename=/data/rules.yml"
      # Watch for Swarm service changes
      - "--providers.swarm.watch=true"
      - "--providers.swarm.exposedbydefault=false"
      # Default network for swarm to connect to services
      # - "--providers.swarm.network=enumverse_frontend_net"
      # Dynamic configuation file provider 
      # - "--providers.file.directory=/var/traefik/data"
      # - "--providers.file.watch=true"
      # HTTP Entrypoints
      - "--entrypoints.web.address=:80"
      # HTTP to HTTPS redirection
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      # HTTPS Entrypoint
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      # SSL/TLS Properties
      # - "--entrypoints.web.http.tls.certResolver=cloudflare"
      - "--entrypoints.websecure.http.tls.certResolver=cloudflare"
      # - "--entrypoints.websecure.http.tls.domains[0].main=${DOMAIN:?ERROR DOMAIN NOT SET}"
      # - "--entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN:?ERROR DOMAIN NOT SET}"
      - "--certificatesresolvers.cloudflare.acme.email=${TF_EMAIL:-labs@semicolon.africa}"
      - "--certificatesresolvers.cloudflare.acme.storage=/var/traefik/certs/cloudflare-acme.json"
      - "--certificatesresolvers.cloudflare.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.cloudflare.acme.keyType=EC256"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=${TF_DNS_PROVIDER:-cloudflare}"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=${TF_DNS_RESOLVER:-1.1.1.1:53,1.0.0.1:53}"
      - "--serverstransport.insecureskipverify=true"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.backend=dashboard"
        - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.entrypoints=web"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.tls=true"
        # - "traefik.http.routers.traefik.middlewares=authelia@docker"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      update_config:
        failure_action: rollback
        order: start-first
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
        monitor: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s

networks:
  edge:
    external: true  
    attachable: true
