#!/bin/bash
set -a
source .env
set +a
PGUID=70
PGGID=70
mkdir -p ${DATA_VOLUME_PG?[ERROR] DATA_VOLUME_PG NOT SET}/pg-0/pgdata
mkdir -p ${DATA_VOLUME_PG?[ERROR] DATA_VOLUME_PG NOT SET}/pg-1/pgdata
mkdir -p ${DATA_VOLUME_PG?[ERROR] DATA_VOLUME_PG NOT SET}/pg-2/pgdata

mkdir -p ${CONF_VOLUME_PG?[ERROR] DATA_VOLUME_PG NOT SET}

chown -R $PGUID:$PGGID ${DATA_VOLUME_PG}
chown -R $PGUID:$PGGID ${CONF_VOLUME_PG}
chmod -R 0775 ${CONF_VOLUME_PG}

mkdir -p ${DATA_VOLUME_KC:?[ERROR] DATA_VOLUME_KC NOT SET}/data
chmod -R 0775 ${DATA_VOLUME_KC}

mkdir -p ${CONF_VOLUME_KC:?[ERROR] CONF_VOLUME_KC NOT SET}
chmod -R 0775 ${CONF_VOLUME_KC}


mkdir -p ${DATA_VOLUME_PS:?[ERROR] DATA_VOLUME_PS NOT SET}/zookeeper
mkdir -p ${DATA_VOLUME_PS:?[ERROR] DATA_VOLUME_PS NOT SET}/bookkeeper
chmod -R 0775 ${DATA_VOLUME_PS}