#!/bin/bash
set -a
source ./.env
set +a
PGUID=999
PGGID=999
mkdir -p ${DATA_VOLUME:?ERROR DATA_VOLUME NOT SET}/mg{1..3}
mkdir -p ${CONF_VOLUME:?ERROR CONF_VOLUME NOT SET}
chown -R $PGUID:$PGGID ${DATA_VOLUME?[ERROR] DATA_VOLUME NOT SET}
chown -R $PGUID:$PGGID ${CONF_VOLUME?[ERROR] CONF_VOLUME NOT SET}
chmod -R 0777 ${DATA_VOLUME}
chmod -R 0777 ${CONF_VOLUME}
