networks:
  enumverse_mongodb_net:
    external: true
    attachable: true

services:
  mg1:
    container_name: mg1
    image: ${MONGO_IMAGE:?ERROR MONGO_IMAGE NOT SET}
    ports:
      - :${MONGO_PORT:?ERROR MONGO_PORT NOT SET}
    volumes:
      - ${DATA_VOLUME:?ERROR DATA_VOLUME NOT SET}/mg1:/data/db
      - ${CONF_VOLUME:?ERROR DATA_VOLUME NOT SET}/keyfile.pem:/data/keyfile.pem
    environment:
      - TZ=Africa/Lagos
      - MONGO_PORT=${MONGO_PORT:?ERROR MONGO_PORT NOT SET}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:?ERROR MONGO_INITDB_ROOT_USERNAME NOT SET}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:?ERROR MONGO_INITDB_ROOT_PASSWORD NOT SET}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:?ERROR MONGO_INITDB_DATABASE NOT SET}
      - MONGO_USERNAME=${MONGO_USERNAME:?ERROR MONGO_USERNAME NOT SET}
      - MONGO_PASSWORD=${MONGO_PASSWORD:?ERROR MONGO_PASSWORD NOT SET}
      - MONGO_REPLSET=${MONGO_REPLSET:?ERROR MONGO_REPLSET NOT SET}
      - DATABASE_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_INITDB_DATABASE}?authSource=admin
    networks:
      - enumverse_mongodb_net
    command: |
      mongod 
      --replSet ${MONGO_REPLSET} 
      --port ${MONGO_PORT}
      --keyFile /data/keyfile.pem

  mg2:
    container_name: mg2
    image: ${MONGO_IMAGE:?ERROR MONGO_IMAGE NOT SET}
    ports:
      - :${MONGO_PORT:?ERROR MONGO_PORT NOT SET}
    volumes:
      - ${DATA_VOLUME:?ERROR DATA_VOLUME NOT SET}/mg2:/data/db
      - ${CONF_VOLUME:?ERROR DATA_VOLUME NOT SET}/keyfile.pem:/data/keyfile.pem
    environment:
      - TZ=Africa/Lagos
      - MONGO_PORT=${MONGO_PORT:?ERROR MONGO_PORT NOT SET}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:?ERROR MONGO_INITDB_ROOT_USERNAME NOT SET}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:?ERROR MONGO_INITDB_ROOT_PASSWORD NOT SET}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:?ERROR MONGO_INITDB_DATABASE NOT SET}
      - MONGO_USERNAME=${MONGO_USERNAME:?ERROR MONGO_USERNAME NOT SET}
      - MONGO_PASSWORD=${MONGO_PASSWORD:?ERROR MONGO_PASSWORD NOT SET}
      - MONGO_REPLSET=${MONGO_REPLSET:?ERROR MONGO_REPLSET NOT SET}
      - DATABASE_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_INITDB_DATABASE}?authSource=admin
    networks:
      - enumverse_mongodb_net
    command: |
      mongod 
      --replSet ${MONGO_REPLSET} 
      --port ${MONGO_PORT}
      --keyFile /data/keyfile.pem

  mg3:
    container_name: mg3
    image: ${MONGO_IMAGE:?ERROR MONGO_IMAGE NOT SET}
    ports:
      - :${MONGO_PORT:?ERROR MONGO_PORT NOT SET}
    volumes:
      - ${DATA_VOLUME:?ERROR DATA_VOLUME NOT SET}/mg3:/data/db
      - ${CONF_VOLUME:?ERROR DATA_VOLUME NOT SET}/keyfile.pem:/data/keyfile.pem
    environment:
      - TZ=Africa/Lagos
      - MONGO_PORT=${MONGO_PORT:?ERROR MONGO_PORT NOT SET}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:?ERROR MONGO_INITDB_ROOT_USERNAME NOT SET}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:?ERROR MONGO_INITDB_ROOT_PASSWORD NOT SET}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:?ERROR MONGO_INITDB_DATABASE NOT SET}
      - MONGO_USERNAME=${MONGO_USERNAME:?ERROR MONGO_USERNAME NOT SET}
      - MONGO_PASSWORD=${MONGO_PASSWORD:?ERROR MONGO_PASSWORD NOT SET}
      - MONGO_REPLSET=${MONGO_REPLSET:?ERROR MONGO_REPLSET NOT SET}
      - DATABASE_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_INITDB_DATABASE}?authSource=admin
    networks:
      - enumverse_mongodb_net
    command: |
      mongod 
      --replSet ${MONGO_REPLSET} 
      --port ${MONGO_PORT}
      --keyFile /data/keyfile.pem

  mgsetup:
    image: ${MONGO_IMAGE:?ERROR MONGO_IMAGE NOT SET}
    volumes:
      - ${CONF_VOLUME:?ERROR DATA_VOLUME NOT SET}/00_init_mongodb.sh:/data/00_init_mongodb.sh
    environment:
      - TZ=Africa/Lagos
      - MONGO_PORT=${MONGO_PORT:?ERROR MONGO_PORT NOT SET}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:?ERROR MONGO_INITDB_ROOT_USERNAME NOT SET}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:?ERROR MONGO_INITDB_ROOT_PASSWORD NOT SET}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:?ERROR MONGO_INITDB_DATABASE NOT SET}
      - MONGO_USERNAME=${MONGO_USERNAME:?ERROR MONGO_USERNAME NOT SET}
      - MONGO_PASSWORD=${MONGO_PASSWORD:?ERROR MONGO_PASSWORD NOT SET}
      - MONGO_REPLSET=${MONGO_REPLSET:?ERROR MONGO_REPLSET NOT SET}
    networks:
      - enumverse_mongodb_net
    entrypoint: ["/bin/bash", "/data/00_init_mongodb.sh"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

  mgexpress:
    image: mongo-express:latest
    ports:
      - 8081:8081
    networks:
      - enumverse_mongodb_net
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXP_USERNAME:?ERROR MONGOEXP_USERNAME NOT SET}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXP_PASSWORD:?ERROR MONGOEXP_PASSWORD NOT SET}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mg1:${MONGO_PORT},mg2:${MONGO_PORT},mg3:${MONGO_PORT}/?replicaSet=${MONGO_REPLSET}&readPreference=primaryPreferred
    depends_on:
      - mg1