#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER ${IDM_DB_USERNAME}  WITH ENCRYPTED PASSWORD '${IDM_DB_PASSWORD}';
        CREATE DATABASE ${IDM_DB_DATABASE};
        GRANT ALL PRIVILEGES ON DATABASE ${IDM_DB_DATABASE} TO ${IDM_DB_USERNAME};
EOSQL